create database customer_behaviour;

--To see whole dataset
select * from customer;

 
--Q1. What is the total revenue generated by male vs. female customers?
select gender, 
	   sum(purchase_amount) as [Total Revenue]
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from customer
where (discount_applied = 'Yes')
	and purchase_amount > (
	select avg(purchase_amount)
	from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select
top 5 item_purchased as [Product],
round(avg(review_rating), 2) as [Avg Review Rating]
from customer
group by item_purchased
order by [Avg Review Rating] desc;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select 
shipping_type,
round(avg(purchase_amount),2) as [Avg Purchase Amount]
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select
subscription_status,
round(avg(purchase_amount), 2) as [Avg Spend],
round(sum(purchase_amount), 2) as [Total Revenue] 
from customer
group by subscription_status;

--Subscribers and non-subscribers have a similar average purchase amount (~59). 
--However, non-subscribers contribute substantially higher total revenue (170,436) than subscribers (62,645), 
--indicating that the non-subscriber segment accounts for a larger share of overall sales.


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 
item_purchased as [Products],
cast(
	ROUND(
		SUM(case when discount_applied = 'Yes' then 1 else 0 end) * 100.0
		/ COUNT(*), 
		2
	) as decimal(5,2)
) as [Discount percentage]
from customer
group by item_purchased
order by [Discount percentage] desc;



--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

-- with Subquery
select 
case 
	when previous_purchases <= 10 then 'New Customer'
	when (previous_purchases > 10) and (previous_purchases < 30) then 'Returning customer'
	else 'Loyal customer'
end as [customer segment],
COUNT(*)
from customer
group by 
	case 
	when previous_purchases <= 10 then 'New Customer'
	when (previous_purchases > 10) and (previous_purchases < 30) then 'Returning customer'
	else 'Loyal customer'
end 

-- with CTEs 
with customer_segment as
(
select *,
	case 
		when previous_purchases <= 10 then 'New Customer'
		when (previous_purchases > 10) and (previous_purchases < 30) then 'Returning customer'
		else 'Loyal customer'
	end as [segment]
from customer
)
select
segment,
COUNT(*) as [Count of segment]
from customer_segment
group by segment;

-- Note: Always prefer CTEs over subquery for better readbility.



--Q8. What are the top 3 most purchased products within each category? 
with ctes as 
(
	select 
		category,
		item_purchased,
		count(*) as [purchase count]  
	from customer
	group by category, item_purchased
),
ranked_products as 
(
	select
		category,
		item_purchased,
		[purchase count],
		ROW_NUMBER() over (partition by category 
						   order by [purchase count] desc) as rn
		from ctes
)
select
	category,
	item_purchased,
	[purchase count]  
from ranked_products
where rn <= 3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
with customer_segment as
(
	select
	subscription_status,
		case
			when previous_purchases > 5 then 'repeat buyers'
			else 'non-repeat buyers'
		end as customer_type
	from customer
),
subscription_counts as
(
	select
	customer_type,
	subscription_status,
	COUNT(*) as [customer type count]
	from customer_segment
	group by subscription_status, customer_type
)
select 
	customer_type,
	sum([customer type count]) as [customer count],
	cast(SUM(CASE WHEN subscription_status = 'Yes' THEN [customer type count] else 0 END) * 100.0
	/
	SUM([customer type count]) as decimal(5,2)) as subscription_rate
from subscription_counts
group by customer_type

-- Yes, the repeat buyers are more likely to subscribe(27.56%) than non-repeat buyers(22.41%).


--Q10. What is the revenue contribution of each age group? 
with revenue_cte as 
(
	select 
		age_group,
		SUM(purchase_amount) as [Total Revenue]
	from customer
	group by age_group
)
select 
	age_group,
	cast(
		[Total Revenue] * 100.0
		/ SUM([Total Revenue]) over()
		as decimal(5,2)
		) as revenue_contribution
from revenue_cte;

-- Young Adult have highest revenue contribution(26.66%) while senior have lowest contribution(23.92%)
